---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-a
spec:
  replicas: 5
  selector:
    matchLabels:
      name: servicea
  template:
    metadata:
      labels:
        name: servicea
    spec:
      containers:
      - name: servicea
        image: servicea
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
spec:
  replicas: 5
  selector:
    matchLabels:
      name: serviceb
  template:
    metadata:
      labels:
        name: serviceb
    spec:
      containers:
      - name: serviceb
        image: serviceb
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  selector:
    name: deployment-a
  ports:
  - name: http
    port: 3000
    targetPort: 80
